on:
  release:
    types: [ created ]

jobs:
  go-binary-release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [ amd64, arm, arm64 ]
    steps:
      - uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libnotify-dev libpulse-dev libmp3lame-dev
          version: 1.0
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: ${{ matrix.goarch }}
          asset_name: pulseclip.${{ matrix.goarch }}
          binary_name: "pulseclip"
          extra_files: LICENSE README.md pulseclip.desktop
          sha256sum: true
          md5sum: false
          overwrite: true